import { integer, pgView, text, timestamp, uuid } from "drizzle-orm/pg-core";

export const factPRDiscoveryFunnelEvents = pgView("fact_pr_discovery_funnel_event", {
  eventId: uuid("event_id").notNull(),
  eventName: text("event_name").notNull(),
  eventVersion: integer("event_version").notNull(),
  journeyId: uuid("journey_id").notNull(),
  traceId: text("trace_id"),
  occurredAt: timestamp("occurred_at", { withTimezone: true }).notNull(),
  stepKey: text("step_key").notNull(),
  prType: text("pr_type"),
  viewMode: text("view_mode"),
  origin: text("origin"),
  prId: integer("pr_id"),
  rank: integer("rank"),
  action: text("action"),
  outcome: text("outcome"),
  handoffReason: text("handoff_reason"),
  routePath: text("route_path"),
  routeName: text("route_name"),
  spm: text("spm"),
  sourceQr: text("source_qr"),
  routeContextStatus: text("route_context_status").notNull(),
  anonymousId: text("anonymous_id"),
  authenticatedUserHash: text("authenticated_user_hash"),
  authContextStatus: text("auth_context_status").notNull(),
}).existing();

export const factPRJoinFunnelEvents = pgView("fact_pr_join_funnel_event", {
  eventId: uuid("event_id").notNull(),
  eventName: text("event_name").notNull(),
  eventVersion: integer("event_version").notNull(),
  journeyId: uuid("journey_id").notNull(),
  traceId: text("trace_id"),
  occurredAt: timestamp("occurred_at", { withTimezone: true }).notNull(),
  routePath: text("route_path"),
  routeName: text("route_name"),
  spm: text("spm"),
  sourceQr: text("source_qr"),
  anonymousId: text("anonymous_id"),
  authenticatedUserHash: text("authenticated_user_hash"),
  routeContextStatus: text("route_context_status").notNull(),
  authContextStatus: text("auth_context_status").notNull(),
  stepKey: text("step_key"),
}).existing();

export const factPRCreateFunnelEvents = pgView("fact_pr_create_funnel_event", {
  eventId: uuid("event_id").notNull(),
  eventName: text("event_name").notNull(),
  eventVersion: integer("event_version").notNull(),
  journeyId: uuid("journey_id").notNull(),
  traceId: text("trace_id"),
  occurredAt: timestamp("occurred_at", { withTimezone: true }).notNull(),
  routePath: text("route_path"),
  routeName: text("route_name"),
  spm: text("spm"),
  sourceQr: text("source_qr"),
  anonymousId: text("anonymous_id"),
  authenticatedUserHash: text("authenticated_user_hash"),
  routeContextStatus: text("route_context_status").notNull(),
  authContextStatus: text("auth_context_status").notNull(),
  stepKey: text("step_key"),
  creationPath: text("creation_path"),
}).existing();

export const factUserRetentionActivityEvents = pgView("fact_user_retention_activity_event", {
  eventId: uuid("event_id").notNull(),
  eventName: text("event_name").notNull(),
  journeyId: uuid("journey_id").notNull(),
  occurredAt: timestamp("occurred_at", { withTimezone: true }).notNull(),
  anonymousId: text("anonymous_id"),
  authenticatedUserHash: text("authenticated_user_hash"),
  identityKey: text("identity_key"),
}).existing();
